### PR TITLE
Investigation of slow overlap test

### PR DESCRIPTION
**Pull request by AndreiPashkin**
Do not merge plz

### CODE REVIEW

**Comment by AndrewPashkin** [comment]
Interesting observation - it seems, like the test is failing only in coverage builds:
https://travis-ci.org/ionelmc/python-redis-lock/jobs/98139300
https://travis-ci.org/ionelmc/python-redis-lock/jobs/96441570
https://travis-ci.org/ionelmc/python-redis-lock/jobs/96441435
https://travis-ci.org/ionelmc/python-redis-lock/jobs/95770166
https://travis-ci.org/ionelmc/python-redis-lock/jobs/95769577
https://travis-ci.org/ionelmc/python-redis-lock/jobs/95769583
https://travis-ci.org/ionelmc/python-redis-lock/jobs/95764563
https://travis-ci.org/ionelmc/python-redis-lock/jobs/98110256
https://travis-ci.org/ionelmc/python-redis-lock/jobs/98110258

I didn't managed to find any `nocov` build where this test was timed out.

**Comment by ionelmc** [comment]
Yes, using sys.settrace (what coverage uses) basically disables the JIT, making PyPy significantly slower than CPython. See http://pypy.org/performance.html#frame-introspection-and-tracing-are-slow

**Comment by AndrewPashkin** [comment]
Interesting, that this is occurs randomly - look at this:
https://travis-ci.org/ionelmc/python-redis-lock/builds/99336521

Other PyPy coverage build are executed in normal times.

**Comment by ionelmc** [comment]
My theory is that Travis is just randomly slow (cause lots of stuff runs on the same metal).

**Comment by AndrewPashkin** [comment]
It should be 10x slow to make this test be timed out

**Comment by AndrewPashkin** [comment]
Very strange, it just stops spawning new processes:
https://travis-ci.org/ionelmc/python-redis-lock/jobs/99429436
https://travis-ci.org/ionelmc/python-redis-lock/jobs/99427820
https://travis-ci.org/ionelmc/python-redis-lock/jobs/99430751

It spawns 70-80 processes and then freezes.

**Comment by ionelmc** [comment]
Could it be some ceiling due to memory use? Eg, high memory use => starts swapping => everything is suddenly very slow

**Comment by AndrewPashkin** [comment]
Do you have an idea of how to debug this?

**Comment by ionelmc** [comment]
If there's indeed a bug somewhere I'd try to reproduce locally.

If it can't be reproduced locally then you gotta start somewhere:

* Ssh access to the Travis instance: https://gist.github.com/jedi4ever/7677d62f1414c28a1a8c
* "Headless debugging" - strace stuff, upload logs somewhere. I did that in the past (see some of the commented stuff here: https://github.com/ionelmc/python-manhole/commit/3ce2cba07da4d6b9383c4f434e1d97a0358d4f45) but it's quite cumbersome. You'd have to change that anyway to do the upload via an alarm signal handler (set it to fire right before Travis would declare the build stuck).

Another idea is to print something on stdout from time to time, so Travis don't declare the build stuck. Just to see if the test is really stuck or just slow.

**Comment by AndrewPashkin** [comment]
Maybe just use threads?

**Comment by ionelmc** [comment]
Threads don't provide parallelism (cause GIL), they only provide concurrency. That's why I didn't use them for the integration tests.

Check the GIL talks here: http://pymust.watch/

**Comment by AndrewPashkin** [comment]
Yeah, and it's impossible to terminate them at cleanup.

**Comment by ionelmc** [comment]
Do you want to do anything more here? At at least, anything to be included in 3.0?

**Comment by AndrewPashkin** [comment]
Now this issue magically disappeared.

**Comment by ionelmc** [comment]
Timing-sensitive perhaps? Prints can cause sideeffects (a print may block for varying amounts of time depending on pty). I suppose you could print to a file maybe? Just to rule out that Travis does anything weird/slow with the output pty.

**Comment by AndrewPashkin** [comment]
The issue is gone.

**Comment by AndrewPashkin** [comment]
@ionelmc, what do you think, is it worth to enable the test now for PyPy envs?

**Comment by ionelmc** [comment]
If it pass, sure, why not. Let me restart the job a couple of times to see if it's really passing.

**Pull request closed without merging**
