### PR TITLE
Simplify Tox configuration

### PR DESCRIPTION
**Pull request by AndrewPashkin**
Replaces copy-pasted Tox environments with [parametrized environments](http://tox.readthedocs.org/en/latest/config.html#generating-environments-conditional-settings).

### CODE REVIEW

**Comment by ionelmc** [comment]
Currently `tox.ini` is generated from this: https://github.com/ionelmc/python-redis-lock/blob/master/setup.cfg#L63-L86 (with a template in `ci/templates`). Not sure if generative tox config can reproduce that matrix ....

**Comment by AndrewPashkin** [comment]
Wow, I didn't noticed that, looks nice. The point is - run Django-related tests on any Python except 2.6? If yes - Tox can do that.

**Comment by AndrewPashkin** [comment]
I also think, that there is no need to have virtual envs with and without coverage, run tests and collect coverage at the same time should be ok and it will be speed up CI.

**Comment by ionelmc** [comment]
I have been burnt in the past by issues (like race condition) creeping up
only when coverage is on or vice-versa.


Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Pull request closed without merging**
