### PR TITLE
Remove un-necessary check. 

### PR DESCRIPTION
**Pull request by ionelmc**
Ref #48.

### CODE REVIEW

**Comment by georgeyk** [comment]
@ionelmc What do you think about remove this check too https://github.com/ionelmc/python-redis-lock/blob/remove-unnecessary-held-check/src/redis_lock/__init__.py#L161 ?

It opens the possibility to use a fake/dummy redis server implementation[1] to write unittests without a real redis instance.

[1]: https://github.com/guilleiguaran/fakeredis

**Comment by ionelmc** [comment]
@georgeyk Hmm, we could remove it. Do you need that removal for your own test suite or something like that?

**Comment by georgeyk** [comment]
@ionelmc yes, I think fakeredis could work for me.

**Comment by ionelmc** [comment]
@georgeyk ok, check this new change.

**Comment by georgeyk** [comment]
LGTM :+1:

**Pull request merged**
