### PR TITLE
Locked method

### PR DESCRIPTION
**Pull request by artslob**
This is MR about adding method `locked` as in [threading.Lock](https://docs.python.org/3.8/library/threading.html#threading.Lock.locked).

### CODE REVIEW

**Comment by artslob** [comment]
All tests are passing, but coverage export is failing.

**Comment by artslob** [comment]
@ionelmc What do you think about this PR?

**Comment by ionelmc** [comment]
Closes #69.

**Comment by ionelmc** [comment]
Thanks, I'll fix the coverage problem.

**Pull request merged**
