### PR TITLE
Work in Progess... - Allowing non-blocking controlled execution

### PR DESCRIPTION
**Pull request by victor-torres**
With custom max retries count, retry interval and blocking parameter.

- Feature: done.
- Documenting: pending.

Note: could not run tests with tox on my local OS X machine,  it says redis-server is not running as 'after 10 seconds there's no Running in response'. I'm creating the pull request so that Travis can run tests for me :)

### CODE REVIEW

**Comment by victor-torres** [comment]
Need help with tests:

```AssertionError: Waited 10.00secs but ['Running'] did not appear in output in the given order !```

**Comment by ionelmc** [comment]
Hey, maybe I'm missing something here but what's the actual use case for
this change?

On Tuesday, September 15, 2015, Victor Torres <notifications@github.com>
wrote:

> With custom max retries count, retry interval and blocking parameter.
>
>    - Feature: done.
>    - Documenting: pending.
>
> Note: could not run tests with tox on my local OS X machine, it says
> redis-server is not running as 'after 10 seconds there's no Running in
> response'. I'm creating the pull request so that Travis can run tests for
> me :)
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ionelmc/python-redis-lock/pull/19
> Commit Summary
>
>    - Alowing non-blocking controlled execution with custom max retries
>    count, retry interval and blocking parameter.
>
> File Changes
>
>    - *M* src/redis_lock/__init__.py
>    <https://github.com/ionelmc/python-redis-lock/pull/19/files#diff-0>
>    (29)
>
> Patch Links:
>
>    - https://github.com/ionelmc/python-redis-lock/pull/19.patch
>    - https://github.com/ionelmc/python-redis-lock/pull/19.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ionelmc/python-redis-lock/pull/19>.
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by victor-torres** [comment]
We've used redis lock to avoid duplicated login entries in our MySQL database since unique index was not available in our specific use case. We've used controlled execution, something like this:

```python
with my_lock:
    do_login()
```

Now imagine the following situation:

Client A -> Acquires lock and for any given reason gets suck with the lock, **renewing** it before it expires.
Client B -> Tries to acquire lock **forever**.

We need to return execution after X seconds and return something to the user. Of course we could have used Lock.acquire(), but what does 'with' statements stand for?

And as much as I know, it's not possible to set a retry count for Lock.acquire() or Lock.__enter__().

**Comment by ionelmc** [comment]
So this is more like a `.acquire(block=True, timeout=123)` - or could be better represented as that?

**Comment by ionelmc** [comment]
I think this would be better solved if we use the timeout option for the BLPOP operation (which does the waiting part in acquire).

**Comment by ionelmc** [comment]
So, in https://github.com/ionelmc/python-redis-lock/blob/master/src/redis_lock/__init__.py#L102 BLPOP will use the expire option. Is there a reason you can't use the expire option? For me it seems that it does exactly what you said here:

> Client A -> Acquires lock and for any given reason gets suck with the lock, renewing it before it expires.
Client B -> Tries to acquire lock forever.

> We need to return execution after X seconds and return something to the user. Of course we could have used Lock.acquire(), but what does 'with' statements stand for?

Am I missing something? :grin:

**Comment by victor-torres** [comment]
Makes sense. I can update this pull request tomorrow morning. But do you have any clue for tests? The Travis CI build is also failing :/

**Comment by ionelmc** [comment]
What I'm trying to say is that your use-case is already covered.

If it's really so, and you didn't realize that, then the documentation is lacking badly. I could use some concrete pointers or proposals to improve documentation then.

**Comment by victor-torres** [comment]
Could you give me an example of using controlled executions with a timeout?

And apart de pull request thing, why did tests fail?

**Comment by ionelmc** [comment]
Example:
```python
x = Lock("foobar", expire=3)
x.acquire() # after 3 seconds this get the lock, regardless if someone still holds it.
```

If this doesn't work like that it's a bug.

Regarding the test failure, not really sure, I suspect there's some environment issue (Travis changed something)

**Comment by victor-torres** [comment]
I see. In our use case, Client B **shouldn't** wait for lock forever. Can't see where expire time would help here since blocking defaults to True. 

Remember we'd like to use "with" statement, not lock.acquire with loops or conditionals.

**Comment by ionelmc** [comment]
These two examples are equivalent:
```
x = Lock("foobar", expire=3)
x.acquire() 
# after 3 seconds this get the lock, regardless if someone still holds it.
```
---
```
with Lock("foobar", expire=3):
   print('after 3 seconds this will run, regardless if someone still holds it.')
```

See: https://github.com/ionelmc/python-redis-lock/blob/master/src/redis_lock/__init__.py#L151

**Comment by ionelmc** [comment]
PS. The tests run now (I have accidentally broken an external dependency).

**Comment by victor-torres** [comment]
```python
import time
import redis
import redis_lock

conn = redis.Redis()
with redis_lock.Lock(conn, 'my_lock', expire=3, auto_renewal=True):
    print 'Acquired lock...'
    time.sleep(10)
    print 'Released lock...'
```

In my use case, if Clients A and B run the same piece of code at the same time, only one of them should acquire lock. For example, if Client A acquires lock, Client B should return without executing what's inside of the 'with' statement. 

It would be nice to have a retry count.

**Comment by ionelmc** [comment]
Now I understand what you want, but I don't think it's possible with the context manager api. See http://stackoverflow.com/questions/12594148/skipping-execution-of-with-block (the trace/frame hack is not really acceptable and will perform badly on pypy).

If you can just use the `acquire` method (and I think you can) then we can have a "timeout" argument. I  think that's better than a retry count. We should also use the timeout argument for BLPOP since that'
s more efficient and fair that poll/sleep till some counter depletes.

**Comment by victor-torres** [comment]
I'll implement the timeout with BLPOP and then update this thread. Thanks for your support.

**Comment by victor-torres** [comment]
Created another pull request with the new changes. Closing this one.

**Pull request closed without merging**
