### PR TITLE
Add the debian packaging for redis_lock.

### PR DESCRIPTION
**Pull request by zaurky**

### CODE REVIEW

**Comment by ionelmc** [comment]
Sorry if this sounds obtuse but why does this project need to have deb packaging in the same repo? AFAIK Debian maintainers take releases from PyPI and repackage that ...

**Comment by zaurky** [comment]
Hum, I just needed this cool stuff packaged for debian, and putting a debian/ in the github is one way to do it. So I asked in case someone else needed it. You are the owner and you decide, if you don't want it that's ok, let's just close it, I will manage it on my side.

**Comment by ionelmc** [comment]
Wouldn't it be better if you use the releases instead? I would advise that. That would allow me to do work on master without breaking your stuff.

Not sure if this is the right thing to do but see https://wiki.debian.org/Python/LibraryStyleGuide#debian.2Fwatch

**Comment by zaurky** [comment]
I am not used to use watch, but you're right, that would be way better, I will take a deeper lock on that.
Thanks for the link :)

**Pull request closed without merging**
