### PR TITLE
Simple method to test if lock with given name is applied

### PR DESCRIPTION
**Pull request by mstaniszczak**
PR With simple method, which allow to test if lock with given name is applied in redis.

### CODE REVIEW

**Comment by ionelmc** [comment]
Hello, can you add/extend some tests?

**Comment by mstaniszczak** [comment]
Ahh I missed your message - sorry. Not sure if I'll be able to do this today, but I'll try do my best at tomorrow:)

**Comment by emesik** [comment]
How about those tests? Would be nice to see it merged :)

**Comment by ionelmc** [comment]
@emesik still not seeing any commit with tests?

**Comment by mstaniszczak** [comment]
After veeery long tomorrow;)

**Comment by ionelmc** [comment]
@mstaniszczak Hey, so I've looked a bit and it turns out most lock classes have a locked method (https://docs.python.org/3/search.html?q=locked&check_keywords=yes&area=default) - I think we should stick to that. Can you also update changelog/authors?

**Pull request closed without merging**
