### PR TITLE
Update diagram.

### PR DESCRIPTION
**Pull request by ionelmc**
cc @AndrewPashkin 

doc is at https://docs.google.com/drawings/d/1XZWt0HKdzilDeVp8xbml-lLaXngP3JTVG7f-yE8W8bo/

### CODE REVIEW

**Comment by AndrewPashkin** [comment]
Oops, now you can't make PR's :astonished:

**Comment by ionelmc** [comment]
What do you mean?

**Comment by AndrewPashkin** [comment]
Because the test is failing =)

**Comment by ionelmc** [comment]
We'll cheat. Just this time. :D

**Pull request merged**
