### PR TITLE
Replace EXPIRE with PEXPIRE calls for expiration of signal-lists

### PR DESCRIPTION
**Pull request by AndrewPashkin**
Subj. It will reduce expiration time of lists from a second to one millisecond.

### CODE REVIEW

**Comment by AndrewPashkin** [comment]
@ionelmc Hm, can you check the tests? Something weird happens again

**Comment by ionelmc** [comment]
I suspect this indeed creates some regression. Eg: key is getting expired before any client gets the signal.

**Comment by AndrewPashkin** [comment]
What is the sufficient time then?

**Comment by ionelmc** [comment]
1 second seems safe, but that many not be safe on a very very busy redis server.

Maybe 1 minute? Could also be something configurable ...

**Comment by AndrewPashkin** [comment]
Notice, that signal list `LPUSH`'ed before `PEXPIRE` call

**Comment by ionelmc** [comment]
> Notice, that signal list LPUSH'ed before PEXPIRE call

Yes, but since the script is atomic that LPUSH won't do anything till script ends. So if script and comands that are queued before BLPOP take more than what you have set for expire then we have a big problem, BLPOP won't have anything to POP from

**Comment by AndrewPashkin** [comment]
But if commands before `LPUSH` take much time, `PEXPIRE` won't be called too.

**Comment by ionelmc** [comment]
> But if commands before LPUSH take much time, PEXPIRE won't be called too.

What do you mean?

**Comment by AndrewPashkin** [comment]
I mean. that order of commands is preserved regardless of execution time

**Comment by AndrewPashkin** [comment]
And `PEXPIRE` always gets called in the end

**Comment by AndrewPashkin** [comment]
I think it's possible to make an experiment by placing analog of `time.sleep()` in Lua after `PEXPIRE`.

**Comment by ionelmc** [comment]
Feel free too push whatever you want here then :)

**Comment by ionelmc** [comment]
Can we close this?

**Comment by AndrewPashkin** [comment]
So, you theory is, that if one client calls `BLPOP akey 0`, and after that other client executes such script:
```lua
redis.call("lpush", 'akey', 1)
redis.log(redis.LOG_NOTICE, 'such script')
redis.call("pexpire", 'akey', 1)
redis.log(redis.LOG_NOTICE, 'much bugs')
```

the client #1 will not return?

**Comment by AndrewPashkin** [comment]
@ionelmc 
> Yes, but since the script is atomic LPUSH won't do anything till script ends. So if script and comands that are queued before BLPOP take more than what you have set for expire then we have a big problem, BLPOP won't have anything to POP from

But shouldn't `BLPOP` be executed BEFORE execution of script?

**Comment by ionelmc** [comment]
> But shouldn't BLPOP be executed BEFORE execution of script?

As I understood it, and from tests I've seen the handling for "blocked" clients are done after script is run. See: https://github.com/antirez/redis/blob/aa953b6ec3517b74b24e88bb76627faac431e239/src/server.c#L2526

But don't take my word for it. I might be wrong! :)

**Comment by AndrewPashkin** [comment]
@ionelmc 
You are right.

I've made such test:
Client #1 executes `BLPOP akey 0'
Client #2 executes `EVAL "redis.call('lpush', 'akey', 1); redis.log(redis.LOG_NOTICE, 'such script'); redis.call('pexpire', 'akey', 1); for var=1,2000000 do cjson.decode(\'{\"a\":1}\') end; redis.log(redis.LOG_NOTICE, 'much bugs')" 0`

And client #1 never returns. But if remove for loop, it returns.

Very strange, to me it seems like a bug in Redis, actually.

**Comment by AndrewPashkin** [comment]
Maybe it's better to just explicitly make another call to remove a signal list?

**Comment by ionelmc** [comment]
That could work. You're saying replace the expires with a simple remove right?

**Comment by AndrewPashkin** [comment]
Yes, after the transa

**Comment by AndrewPashkin** [comment]
Even more weireder:
Client #1: `BLPOP akey 0`
Client #2: `EVAL "redis.call('lpush', 'akey', 1); redis.call('del', 'akey')" 0`

Client #1 never returns. :astonished:

**Pull request closed without merging**
